---
title: "Support Vector Model"
html_document:
    df_print: paged
editor_options: 
  markdown: 
    wrap: 72
date: "2024-12-07"
---
#Import necessary libraries.
```{r}
library(data.table)
library(e1071)
library(caret)
library(smotefamily)
```
# Load data
```{r}
onlineShopperData <- fread("data/online_shoppers_intention.csv")
```
# Data Preprocessing
```{r}
data_processed <- onlineShopperData[, Revenue := as.factor(Revenue)]
data_processed <- data_processed[, total_Duration := Administrative_Duration + Informational_Duration + ProductRelated_Duration]
data_processed <- data_processed[, proportion_of_duration := ProductRelated_Duration / total_Duration]
data_processed <- data_processed[, c("OperatingSystems", 
                                     "Browser", "Administrative", "Informational", 
                                     "ProductRelated", "Administrative_Duration", 
                                     "Informational_Duration", "ProductRelated_Duration") := NULL]
```
# Rectify issues with NA values
```{r}
data_processed[is.na(data_processed)] <- 0
```

# Splitting the dataset
```{r}
set.seed(123)
sample_size <- floor(0.7 * nrow(data_processed))
train_indices <- sample(seq_len(nrow(data_processed)), size = sample_size)
train_data <- data_processed[train_indices, ]
test_data <- data_processed[-train_indices, ]
```


#Oversampling dataset
```{r}

train_data <- SMOTE(train_data, train_data$Revenue)

```

# Initialize results dataframe
```{r}
results <- data.frame(
  Accuracy = numeric(),
  TPR = numeric(),
  TNR = numeric(),
  F1_Score = numeric()
)

set.seed(71)
```

```{r}

#Tune the SVM parameters

  p_tune <- tune(svm, Revenue~., data = train_data, 
              ranges = list(gamma = 2^(-1:1), cost = 2^(2:4)),
              tunecontrol = tune.control(sampling = "fix")
             )

summary(p_tune)
plot(p_tune)

```

```{r}
#Train the SVM

svm_model <- svm(Revenue ~ ., data = train_data, kernel = "radial", cost=p_tune$best.parameters[[2]], gamma=p_tune$best.parameters[[1]])



# test with train data

    
# Predict on test data
predictions <- predict(svm_model, test_data)
cm <- confusionMatrix(predictions, test_data$Revenue)
    
# Extract confusion matrix metrics
tp <- cm$table[2, 2]  # True Positives
tn <- cm$table[1, 1]  # True Negatives
fp <- cm$table[1, 2]  # False Positives
fn <- cm$table[2, 1]  # False Negatives
    
# Calculate metrics
accuracy <- cm$overall['Accuracy']
tpr <- tp / (tp + fn)  # True Positive Rate
tnr <- tn / (tn + fp)  # True Negative Rate
precision <- tp / (tp + fp)
recall <- tpr  # Recall is the same as TPR
f1_score <- 2 * (precision * recall) / (precision + recall)
    
# Store results
results <- rbind(results, data.frame(Accuracy = accuracy, TPR = tpr, TNR = tnr, F1_Score = f1_score))

```
# Print results
```{r}
print(results)
```
